### ISSUE TITLE
.py extension

### ISSUE THREAD

**Issue by csapot** [ZJUGiveLab/UNet-Version#2]
is there a reason why the source codes don't end with .py extension?
after renaming, they are OK

**Comment by ZJUGiveLab** [comment]
Thanks for your suggestion, I have modified it.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Tamas Gabor CSAPO"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月4日(星期一) 晚上6:10
收件人:&nbsp;"ZJUGiveLab/UNet-Version"<UNet-Version@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[ZJUGiveLab/UNet-Version] .py extension (#2)





 
is there a reason why the source codes don't end with .py extension?
 after renaming, they are OK
