### ISSUE TITLE
The number of convolution kernel 

### ISSUE THREAD

**Issue by chenvvenxin** [ZJUGiveLab/UNet-Version#4]
Hi, I found that the number of convolution kernel in your Paper is 64 * 5 (Fig. 2).But in the code 'models/UNet_3Plus.py' , the number list of convolution kernel is [64, 128, 256, 512, 1024]( line 19).So this is the point that bothers me, I want to know which is the correct one.Thx

**Comment by ZJUGiveLab** [comment]
Hi, the [64, 128, 256, 512, 1024]( line 19) is the number list of encoder convolution kernel, while 64 * 5&nbsp; in the paper is the number of decoder convolution kernel.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ZJUGiveLab/UNet-Version"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月26日(星期天) 下午2:22
收件人:&nbsp;"ZJUGiveLab/UNet-Version"<UNet-Version@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[ZJUGiveLab/UNet-Version] The number of convolution kernel  (#4)





 
Hi, I found that the number of convolution kernel in your Paper is 64 * 5 (Fig. 2).But in the code 'models/UNet_3Plus.py' , the number list of convolution kernel is [64, 128, 256, 512, 1024]( line 19).So this is the point that bothers me, I want to know which is the correct one.Thx
